mp_multiplier = {
    "BrowDownLeft": 2,
    "BrowDownRight": 2,
    "BrowInnerUpRight": 1,
    "BrowInnerUpLeft": 1,
    "BrowOuterUpLeft": 1,
    "BrowOuterUpRight": 1,
    "CheekPuff": 1,
    "CheekSquintLeft": 1,
    "CheekSquintRight": 1,
    "EyeLookDownLeft": 1,
    "EyeLookDownRight": 1,
    "EyeLookInLeft": 1,
    "EyeLookInRight": 1,
    "EyeLookOutLeft": 1,
    "EyeLookOutRight": 1,
    "EyeLookUpLeft": 1.6,
    "EyeLookUpRight": 1.6,
    "EyeSquintLeft": 1,
    "EyeSquintRight": 1,
    "EyeWideLeft": 5,  # this can be much much lower but because glasses it is high
    "EyeWideRight": 5,  # about 5-10 seems to do the trick wo glassses
    "JawForward": 2,
    "JawLeft": 5,
    "JawOpen": 1,
    "JawRight": 5,
    "MouthClosed": 2,
    "MouthDimpleLeft": 6,
    "MouthDimpleRight": 10,
    "MouthFrownLeft": 5,
    "MouthFrownRight": 5,
    "LipFunnel": 1.8,
    "MouthLeft": 1.5,
    "MouthRight": 1.5,
    "LipPucker": 0.7,
    "MouthSmileLeft": 3,
    "MouthSmileRight": 3,
    "MouthStretchLeft": 5,
    "MouthStretchRight": 5,
    "NoseSneerLeft": 4,
    "NoseSneerRight": 4,
    "MouthUpperUpLeft": 1,
    "MouthUpperUpRight": 1,
    "MouthLowerDownLeft": 10,
    "MouthLowerDownRight": 10,
    "MouthPressLeft": 5,
    "MouthPressRight": 5,
}

mp_offset = {
    "BrowDownLeft": 0.1,
    "BrowDownRight": 0.1,
    "BrowInnerUpRight": 0,
    "BrowInnerUpLeft": 0,
    "BrowOuterUpLeft": 0,
    "BrowOuterUpRight": 0,
    "CheekPuff": 0,
    "CheekSquintLeft": 0,
    "CheekSquintRight": 0,
    "EyeLookDownLeft": 0,
    "EyeLookDownRight": 0,
    "EyeLookInLeft": 0,
    "EyeLookInRight": 0,
    "EyeLookOutLeft": 0,
    "EyeLookOutRight": 0,
    "EyeLookUpLeft": 0,
    "EyeLookUpRight": 0,
    "EyeSquintLeft": 0,
    "EyeSquintRight": 0,
    "EyeWideLeft": 0,
    "EyeWideRight": 0,
    "JawForward": 0.25,
    "JawLeft": 0,
    "JawOpen": 0,
    "JawRight": 0,
    "MouthClosed": 0,
    "MouthDimpleLeft": 0,
    "MouthDimpleRight": 0,
    "MouthFrownLeft": 0,
    "MouthFrownRight": 0,
    "LipFunnel": 0,
    "MouthLeft": 0,
    "MouthRight": 0,
    "LipPucker": 0,
    "MouthSmileLeft": 0,
    "MouthSmileRight": 0,
    "MouthStretchLeft": 0,
    "MouthStretchRight": 0,
    "NoseSneerLeft": 0,
    "NoseSneerRight": 0,
    "MouthUpperUpLeft": 0,
    "MouthUpperUpRight": 0,
    "MouthLowerDownLeft": 0,
    "MouthLowerDownRight": 0,
    "MouthPressLeft": 0,
    "MouthPressRight": 0,
}


mp_bound = {
    "BrowDownLeft": [0, 1],
    "BrowDownRight": [0, 1],
    "BrowInnerUpRight": [0, 1],
    "BrowInnerUpLeft": [0, 1],
    "BrowOuterUpLeft": [0, 1],
    "BrowOuterUpRight": [0, 1],
    "CheekPuff": [0, 1],
    "CheekSquintLeft": [0, 1],
    "CheekSquintRight": [0, 1],
    "EyeLookDownLeft": [0, 1],
    "EyeLookDownRight": [0, 1],
    "EyeLookInLeft": [0, 1],
    "EyeLookInRight": [0, 1],
    "EyeLookOutLeft": [0, 1],
    "EyeLookOutRight": [0, 1],
    "EyeLookUpLeft": [0, 1],
    "EyeLookUpRight": [0, 1],
    "EyeSquintLeft": [0, 1],
    "EyeSquintRight": [0, 1],
    "EyeWideLeft": [0, 1],
    "EyeWideRight": [0, 1],
    "JawForward": [0, 1],
    "JawLeft": [0, 1],
    "JawOpen": [0, 1],
    "JawRight": [0, 1],
    "MouthClosed": [0, 1],
    "MouthDimpleLeft": [0, 1],
    "MouthDimpleRight": [0, 1],
    "MouthFrownLeft": [0, 1],
    "MouthFrownRight": [0, 1],
    "LipFunnel": [0, 1],
    "MouthLeft": [0, 1],
    "MouthRight": [0, 1],
    "LipPucker": [0, 1],
    "MouthSmileLeft": [0, 1],
    "MouthSmileRight": [0, 1],
    "MouthStretchLeft": [0, 1],
    "MouthStretchRight": [0, 1],
    "NoseSneerLeft": [0, 1],
    "NoseSneerRight": [0, 1],
    "MouthUpperUpLeft": [0, 1],
    "MouthUpperUpRight": [0, 1],
    "MouthLowerDownLeft": [0, 1],
    "MouthLowerDownRight": [0, 1],
    "MouthPressLeft": [0, 1],
    "MouthPressRight": [0, 1],
}


param_tuning = {
    "BrowDownLeft": {"mul": 2, "offset": 0.1, "min": 0, "max": 1, "cfunct": ""},
    "BrowDownRight": {"mul": 2, "offset": 0.1, "min": 0, "max": 1, "cfunct": ""},
    "BrowInnerUpRight": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "BrowInnerUpLeft": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "BrowOuterUpLeft": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "BrowOuterUpRight": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "CheekPuff": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "CheekSquintLeft": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "CheekSquintRight": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeLookDownLeft": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeLookDownRight": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeLookInLeft": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeLookInRight": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeLookOutLeft": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeLookOutRight": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeLookUpLeft": {"mul": 1.6, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeLookUpRight": {"mul": 1.6, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeSquintLeft": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeSquintRight": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeWideLeft": {"mul": 5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "EyeWideRight": {"mul": 5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "JawForward": {"mul": 2, "offset": 0.25, "min": 0, "max": 1, "cfunct": ""},
    "JawLeft": {"mul": 5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "JawOpen": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "JawRight": {"mul": 5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthClosed": {"mul": 2, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthDimpleLeft": {"mul": 6, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthDimpleRight": {"mul": 10, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthFrownLeft": {"mul": 5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthFrownRight": {"mul": 5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "LipFunnel": {"mul": 1.8, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthLeft": {"mul": 1.5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthRight": {"mul": 1.5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "LipPucker": {"mul": 0.7, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthSmileLeft": {"mul": 3, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthSmileRight": {"mul": 3, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthStretchLeft": {"mul": 5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthStretchRight": {"mul": 5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "NoseSneerLeft": {"mul": 4, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "NoseSneerRight": {"mul": 4, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthUpperUpLeft": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthUpperUpRight": {"mul": 1, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthLowerDownLeft": {"mul": 10, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthLowerDownRight": {"mul": 10, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthPressLeft": {"mul": 5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
    "MouthPressRight": {"mul": 5, "offset": 0, "min": 0, "max": 1, "cfunct": ""},
}

for k, v in mp_multiplier.items():
    param_tuning[k] = {
        "mul": v,
        "offset": mp_offset[k],
        "min": mp_bound[k][0],
        "max": mp_bound[k][1],
        "cfunct": "",
    }

print(param_tuning)
